name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push to gh-pages
      run: |
        tree files -H https://static.csivit.com/ -o files index.html
        git push origin --delete gh-pages || :
        git subtree push --prefix files origin gh-pages
