name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push to gh-pages
      run: |
        sudo apt update
        sudo apt install -y tree
        tree files -H . -o files/index.html
        git config user.name csivitu
        git add files/index.html
        git commit --amend --no-edit
        git push origin `git subtree split --prefix files master`:gh-pages --force
