name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOMEPAGE: https://static.csivit.com/
    steps:
    - uses: actions/checkout@v2
    - name: push to gh-pages
      run: |
        sudo apt update
        sudo apt install -y tree
        tree files -H $HOMEPAGE -o files/index.html
        git push origin --delete gh-pages || :
        git subtree push --prefix files origin gh-pages
